In [3]:
# KNN classification algorithm
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
from sklearn.model_selection import train_test_split

iris_dataset=load_iris()
A_train, A_test, B_train, B_test = train_test_split(iris_dataset["data"], iris_dataset["target"], random_state=0)
kn = KNeighborsClassifier(n_neighbors=1) 
kn.fit(A_train, B_train)

A_new = np.array([[8, 2.5, 1, 1.2]])
prediction = kn.predict(A_new)
print("Predicted target value: {}\n".format(prediction))
print("Predicted feature name: {}\n".format(iris_dataset["target_names"][prediction]))
print("Test score: {:.2f}".format(kn.score(A_test, B_test)))


SyntaxError: invalid non-printable character U+00A0 (1083521222.py, line 9)

In [4]:
from sklearn import datasets
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
# Stacking the Iris dataset
iris = datasets.load_iris()
# A -> features and B -> label
A = iris.data
B = iris.target
# Breaking A and B into train and test data
A_train, A_test, B_train, B_test = train_test_split(A, B, random_state = 0)
# Training a linear SVM classifier
from sklearn.svm import SVC
svm_model_linear = SVC(kernel = 'linear', C = 1).fit(A_train, B_train)
svm_predictions = svm_model_linear.predict(A_test)
# Model accuracy for A_test
accuracy = svm_model_linear.score(A_test, B_test)
# Creating a confusion matrix
cm = confusion_matrix(B_test, svm_predictions)

In [6]:
print(cm)

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


In [9]:
dic = {1:2, 3:4}
print(dic.get_values())

AttributeError: 'dict' object has no attribute 'get_values'

In [5]:
# import pandas as pd 
# import numpy as np 
# import matplotlib.pyplot as plt 
# dataset = pd.read_csv('...\\User_Data.csv')
# # input 
# x = dataset.iloc[:, [2, 3]].values 
  
# # output 
# y = dataset.iloc[:, 4].values 
# plitting the dataset to train and test. 75% of data is used for training the model and 25% of it is used to test the performance of our model.
# from sklearn.cross_validation import train_test_split 
# xtrain, xtest, ytrain, ytest = train_test_split( 
#         x, y, test_size = 0.25, random_state = 0) 

# from sklearn.preprocessing import StandardScaler 
# sc_x = StandardScaler() 
# xtrain = sc_x.fit_transform(xtrain)  
# xtest = sc_x.transform(xtest) 
  
# print (xtrain[0:10, :]) 
# from sklearn.linear_model import LogisticRegression 
# classifier = LogisticRegression(random_state = 0) 
# classifier.fit(xtrain, ytrain) 

# y_pred = classifier.predict(xtest)

# from sklearn.metrics import confusion_matrix 
# cm = confusion_matrix(ytest, y_pred) 
  
# print ("Confusion Matrix : \n", cm)

# from sklearn.metrics import accuracy_score 
# print ("Accuracy : ", accuracy_score(ytest, y_pred)) 


SyntaxError: invalid non-printable character U+00A0 (4008212744.py, line 7)